#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
Name     : qt6wayland
Version  : 6.6.1
Release  : 4
URL      : https://download.qt.io/official_releases/qt/6.6/6.6.1/submodules/qtwayland-everywhere-src-6.6.1.tar.xz
Source0  : https://download.qt.io/official_releases/qt/6.6/6.6.1/submodules/qtwayland-everywhere-src-6.6.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0 MIT
Requires: qt6wayland-lib = %{version}-%{release}
Requires: qt6wayland-libexec = %{version}-%{release}
Requires: qt6wayland-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : extra-cmake-modules pkgconfig(egl)
BuildRequires : extra-cmake-modules pkgconfig(wayland-client)
BuildRequires : extra-cmake-modules wayland
BuildRequires : glibc-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : pkg-config
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
BuildRequires : qtwayland-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the QtWayland module.
The QtWayland module consists of two parts:
Wayland platform plugin:
Enables Qt applications to be run as Wayland clients.

%package dev
Summary: dev components for the qt6wayland package.
Group: Development
Requires: qt6wayland-lib = %{version}-%{release}
Provides: qt6wayland-devel = %{version}-%{release}
Requires: qt6wayland = %{version}-%{release}

%description dev
dev components for the qt6wayland package.


%package lib
Summary: lib components for the qt6wayland package.
Group: Libraries
Requires: qt6wayland-libexec = %{version}-%{release}
Requires: qt6wayland-license = %{version}-%{release}

%description lib
lib components for the qt6wayland package.


%package libexec
Summary: libexec components for the qt6wayland package.
Group: Default
Requires: qt6wayland-license = %{version}-%{release}

%description libexec
libexec components for the qt6wayland package.


%package license
Summary: license components for the qt6wayland package.
Group: Default

%description license
license components for the qt6wayland package.


%prep
%setup -q -n qtwayland-everywhere-src-6.6.1
cd %{_builddir}/qtwayland-everywhere-src-6.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703012531
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1703012531
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6wayland
cp %{_builddir}/qtwayland-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6wayland/b073f11f0c81a95ab5e32aa6b5d23a5955a95274 || :
cp %{_builddir}/qtwayland-everywhere-src-%{version}/LICENSES/GFDL-1.3-no-invariants-only.txt %{buildroot}/usr/share/package-licenses/qt6wayland/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/qtwayland-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6wayland/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qtwayland-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6wayland/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qtwayland-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6wayland/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/qtwayland-everywhere-src-%{version}/src/3rdparty/protocol/HPND_LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6wayland/c26ed387addfc80ff83f3bd34f777d1f764c0a63 || :
cp %{_builddir}/qtwayland-everywhere-src-%{version}/src/3rdparty/protocol/MIT_LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6wayland/78fef8f56be8b440aa35115b77ac7f968f3974b7 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/qt6/metatypes/qt6waylandclient_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6waylandcompositor_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6waylandeglclienthwintegrationprivate_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6waylandeglcompositorhwintegrationprivate_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6wlshellintegrationprivate_relwithdebinfo_metatypes.json
/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri
/usr/lib64/qt6/modules/WaylandClient.json
/usr/lib64/qt6/modules/WaylandCompositor.json
/usr/lib64/qt6/modules/WaylandEglClientHwIntegrationPrivate.json
/usr/lib64/qt6/modules/WaylandEglCompositorHwIntegrationPrivate.json
/usr/lib64/qt6/modules/WaylandGlobalPrivate.json
/usr/lib64/qt6/modules/WlShellIntegrationPrivate.json

%files dev
%defattr(-,root,root,-)
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qtwaylandclient-config_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qtwaylandclientglobal_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-cursor-shape-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-fractional-scale-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-hardware-integration.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-pointer-gestures-unstable-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-qt-key-unstable-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-qt-text-input-method-unstable-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-qt-toplevel-drag-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-qt-windowmanager.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-server-buffer-extension.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-surface-extension.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-tablet-unstable-v2.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-text-input-unstable-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-text-input-unstable-v2.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-text-input-unstable-v4-wip.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-touch-extension.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-viewporter.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-wayland.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-wp-primary-selection-unstable-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-xdg-output-unstable-v1.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwayland-xdg-shell.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandabstractdecoration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandbuffer_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandclientbufferintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandclientbufferintegrationfactory_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandclientbufferintegrationplugin_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandclientextension_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandclientshellapi_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandclipboard_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandcursor_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddatadevice_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddatadevicemanager_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddataoffer_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddatasource_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddecorationfactory_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddecorationplugin_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddisplay_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylanddnd_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandextendedsurface_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandfractionalscale_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandhardwareintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandinputcontext_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandinputdevice_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandinputdeviceintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandinputdeviceintegrationfactory_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandinputdeviceintegrationplugin_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandinputmethodcontext_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandnativeinterface_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandpointergestures_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandprimaryselectionv1_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandqtkey_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandscreen_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandserverbufferintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandserverbufferintegrationfactory_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandserverbufferintegrationplugin_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshellintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshellintegrationfactory_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshellintegrationplugin_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshellsurface_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshm_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshmbackingstore_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandshmwindow_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandsubsurface_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandsurface_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandtabletv2_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandtextinputinterface_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandtextinputv1_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandtextinputv2_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandtouch_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandviewport_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandvulkaninstance_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandvulkanwindow_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandwindow_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandwindowmanagerintegration_p.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-cursor-shape-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-fractional-scale-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-hardware-integration-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-pointer-gestures-unstable-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-qt-key-unstable-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-qt-text-input-method-unstable-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-qt-toplevel-drag-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-qt-windowmanager-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-server-buffer-extension-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-surface-extension-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-tablet-unstable-v2-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-text-input-unstable-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-text-input-unstable-v2-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-text-input-unstable-v4-wip-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-touch-extension-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-viewporter-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-wayland-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-wp-primary-selection-unstable-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-xdg-output-unstable-v1-client-protocol.h
/usr/include/QtWaylandClient/6.6.1/QtWaylandClient/private/wayland-xdg-shell-client-protocol.h
/usr/include/QtWaylandClient/QWaylandClientExtension
/usr/include/QtWaylandClient/QWaylandClientExtensionTemplate
/usr/include/QtWaylandClient/QtWaylandClient
/usr/include/QtWaylandClient/QtWaylandClientDepends
/usr/include/QtWaylandClient/QtWaylandClientVersion
/usr/include/QtWaylandClient/qtwaylandclient-config.h
/usr/include/QtWaylandClient/qtwaylandclientexports.h
/usr/include/QtWaylandClient/qtwaylandclientglobal.h
/usr/include/QtWaylandClient/qtwaylandclientversion.h
/usr/include/QtWaylandClient/qwaylandclientexport.h
/usr/include/QtWaylandClient/qwaylandclientextension.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qtwaylandcompositor-config_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qtwaylandcompositorglobal_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-hardware-integration.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-idle-inhibit-unstable-v1.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-ivi-application.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-presentation-time.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-qt-key-unstable-v1.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-qt-text-input-method-unstable-v1.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-qt-texture-sharing-unstable-v1.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-qt-windowmanager.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-scaler.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-server-buffer-extension.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-text-input-unstable-v2.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-text-input-unstable-v4-wip.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-touch-extension.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-viewporter.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-wayland.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-xdg-decoration-unstable-v1.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-xdg-output-unstable-v1.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwayland-server-xdg-shell.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandcompositor_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandcompositorextension_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylanddestroylistener_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandidleinhibitv1_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandinputmethodcontrol_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandiviapplication_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandivisurface_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandkeyboard_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandkeymap_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandoutput_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandoutputmode_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandpointer_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandqttextinputmethod_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandqttextinputmethodmanager_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandqtwindowmanager_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandseat_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandshell_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandsurface_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandtextinput_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandtextinputmanager_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandtouch_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandutils_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandview_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandviewporter_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandwlshell_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandxdgdecorationv1_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandxdgoutputv1_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwaylandxdgshell_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlbuffermanager_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlclientbuffer_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlclientbufferintegration_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlclientbufferintegrationfactory_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlclientbufferintegrationplugin_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwldatadevice_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwldatadevicemanager_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwldataoffer_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwldatasource_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlhardwarelayerintegration_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlhardwarelayerintegrationfactory_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlhardwarelayerintegrationplugin_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlhwintegration_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlqtkey_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlqttouch_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlregion_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlserverbufferintegration_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlserverbufferintegrationfactory_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwlserverbufferintegrationplugin_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/qwltextureorphanage_p.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-hardware-integration-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-idle-inhibit-unstable-v1-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-ivi-application-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-presentation-time-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-qt-key-unstable-v1-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-qt-text-input-method-unstable-v1-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-qt-texture-sharing-unstable-v1-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-qt-windowmanager-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-scaler-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-server-buffer-extension-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-text-input-unstable-v2-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-text-input-unstable-v4-wip-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-touch-extension-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-viewporter-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-wayland-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-xdg-decoration-unstable-v1-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-xdg-output-unstable-v1-server-protocol.h
/usr/include/QtWaylandCompositor/6.6.1/QtWaylandCompositor/private/wayland-xdg-shell-server-protocol.h
/usr/include/QtWaylandCompositor/QWaylandBufferRef
/usr/include/QtWaylandCompositor/QWaylandClient
/usr/include/QtWaylandCompositor/QWaylandCompositor
/usr/include/QtWaylandCompositor/QWaylandCompositorExtension
/usr/include/QtWaylandCompositor/QWaylandCompositorExtensionTemplate
/usr/include/QtWaylandCompositor/QWaylandDestroyListener
/usr/include/QtWaylandCompositor/QWaylandDrag
/usr/include/QtWaylandCompositor/QWaylandIdleInhibitManagerV1
/usr/include/QtWaylandCompositor/QWaylandInputMethodControl
/usr/include/QtWaylandCompositor/QWaylandIviApplication
/usr/include/QtWaylandCompositor/QWaylandIviSurface
/usr/include/QtWaylandCompositor/QWaylandKeyboard
/usr/include/QtWaylandCompositor/QWaylandKeymap
/usr/include/QtWaylandCompositor/QWaylandObject
/usr/include/QtWaylandCompositor/QWaylandOutput
/usr/include/QtWaylandCompositor/QWaylandOutputMode
/usr/include/QtWaylandCompositor/QWaylandPointer
/usr/include/QtWaylandCompositor/QWaylandQtTextInputMethod
/usr/include/QtWaylandCompositor/QWaylandQtTextInputMethodManager
/usr/include/QtWaylandCompositor/QWaylandQtWindowManager
/usr/include/QtWaylandCompositor/QWaylandResource
/usr/include/QtWaylandCompositor/QWaylandSeat
/usr/include/QtWaylandCompositor/QWaylandShell
/usr/include/QtWaylandCompositor/QWaylandShellSurface
/usr/include/QtWaylandCompositor/QWaylandShellSurfaceTemplate
/usr/include/QtWaylandCompositor/QWaylandShellTemplate
/usr/include/QtWaylandCompositor/QWaylandSurface
/usr/include/QtWaylandCompositor/QWaylandSurfaceGrabber
/usr/include/QtWaylandCompositor/QWaylandSurfaceRole
/usr/include/QtWaylandCompositor/QWaylandTextInput
/usr/include/QtWaylandCompositor/QWaylandTextInputManager
/usr/include/QtWaylandCompositor/QWaylandTouch
/usr/include/QtWaylandCompositor/QWaylandView
/usr/include/QtWaylandCompositor/QWaylandViewporter
/usr/include/QtWaylandCompositor/QWaylandWlShell
/usr/include/QtWaylandCompositor/QWaylandWlShellSurface
/usr/include/QtWaylandCompositor/QWaylandXdgDecorationManagerV1
/usr/include/QtWaylandCompositor/QWaylandXdgOutputManagerV1
/usr/include/QtWaylandCompositor/QWaylandXdgOutputV1
/usr/include/QtWaylandCompositor/QWaylandXdgPopup
/usr/include/QtWaylandCompositor/QWaylandXdgShell
/usr/include/QtWaylandCompositor/QWaylandXdgSurface
/usr/include/QtWaylandCompositor/QWaylandXdgToplevel
/usr/include/QtWaylandCompositor/QtWaylandCompositor
/usr/include/QtWaylandCompositor/QtWaylandCompositorDepends
/usr/include/QtWaylandCompositor/QtWaylandCompositorVersion
/usr/include/QtWaylandCompositor/qtwaylandcompositor-config.h
/usr/include/QtWaylandCompositor/qtwaylandcompositorexports.h
/usr/include/QtWaylandCompositor/qtwaylandcompositorglobal.h
/usr/include/QtWaylandCompositor/qtwaylandcompositorversion.h
/usr/include/QtWaylandCompositor/qtwaylandqmlinclude.h
/usr/include/QtWaylandCompositor/qwaylandbufferref.h
/usr/include/QtWaylandCompositor/qwaylandclient.h
/usr/include/QtWaylandCompositor/qwaylandcompositor.h
/usr/include/QtWaylandCompositor/qwaylandcompositorextension.h
/usr/include/QtWaylandCompositor/qwaylanddestroylistener.h
/usr/include/QtWaylandCompositor/qwaylanddrag.h
/usr/include/QtWaylandCompositor/qwaylandexport.h
/usr/include/QtWaylandCompositor/qwaylandidleinhibitv1.h
/usr/include/QtWaylandCompositor/qwaylandinputmethodcontrol.h
/usr/include/QtWaylandCompositor/qwaylandiviapplication.h
/usr/include/QtWaylandCompositor/qwaylandivisurface.h
/usr/include/QtWaylandCompositor/qwaylandkeyboard.h
/usr/include/QtWaylandCompositor/qwaylandkeymap.h
/usr/include/QtWaylandCompositor/qwaylandoutput.h
/usr/include/QtWaylandCompositor/qwaylandoutputmode.h
/usr/include/QtWaylandCompositor/qwaylandpointer.h
/usr/include/QtWaylandCompositor/qwaylandqttextinputmethod.h
/usr/include/QtWaylandCompositor/qwaylandqttextinputmethodmanager.h
/usr/include/QtWaylandCompositor/qwaylandqtwindowmanager.h
/usr/include/QtWaylandCompositor/qwaylandresource.h
/usr/include/QtWaylandCompositor/qwaylandseat.h
/usr/include/QtWaylandCompositor/qwaylandshell.h
/usr/include/QtWaylandCompositor/qwaylandshellsurface.h
/usr/include/QtWaylandCompositor/qwaylandsurface.h
/usr/include/QtWaylandCompositor/qwaylandsurfacegrabber.h
/usr/include/QtWaylandCompositor/qwaylandtextinput.h
/usr/include/QtWaylandCompositor/qwaylandtextinputmanager.h
/usr/include/QtWaylandCompositor/qwaylandtouch.h
/usr/include/QtWaylandCompositor/qwaylandview.h
/usr/include/QtWaylandCompositor/qwaylandviewporter.h
/usr/include/QtWaylandCompositor/qwaylandwlshell.h
/usr/include/QtWaylandCompositor/qwaylandxdgdecorationv1.h
/usr/include/QtWaylandCompositor/qwaylandxdgoutputv1.h
/usr/include/QtWaylandCompositor/qwaylandxdgshell.h
/usr/include/QtWaylandEglClientHwIntegration/6.6.1/QtWaylandEglClientHwIntegration/private/qwaylandeglclientbufferintegration_p.h
/usr/include/QtWaylandEglClientHwIntegration/6.6.1/QtWaylandEglClientHwIntegration/private/qwaylandeglinclude_p.h
/usr/include/QtWaylandEglClientHwIntegration/6.6.1/QtWaylandEglClientHwIntegration/private/qwaylandeglwindow_p.h
/usr/include/QtWaylandEglClientHwIntegration/6.6.1/QtWaylandEglClientHwIntegration/private/qwaylandglcontext_p.h
/usr/include/QtWaylandEglClientHwIntegration/QtWaylandEglClientHwIntegration
/usr/include/QtWaylandEglClientHwIntegration/QtWaylandEglClientHwIntegrationDepends
/usr/include/QtWaylandEglClientHwIntegration/QtWaylandEglClientHwIntegrationVersion
/usr/include/QtWaylandEglClientHwIntegration/qtwaylandeglclienthwintegrationversion.h
/usr/include/QtWaylandEglCompositorHwIntegration/6.6.1/QtWaylandEglCompositorHwIntegration/private/waylandeglclientbufferintegration_p.h
/usr/include/QtWaylandEglCompositorHwIntegration/QtWaylandEglCompositorHwIntegration
/usr/include/QtWaylandEglCompositorHwIntegration/QtWaylandEglCompositorHwIntegrationDepends
/usr/include/QtWaylandEglCompositorHwIntegration/QtWaylandEglCompositorHwIntegrationVersion
/usr/include/QtWaylandEglCompositorHwIntegration/qtwaylandeglcompositorhwintegrationversion.h
/usr/include/QtWaylandGlobal/6.6.1/QtWaylandGlobal/private/qtwaylandglobal-config_p.h
/usr/include/QtWaylandGlobal/QtWaylandGlobal
/usr/include/QtWaylandGlobal/QtWaylandGlobalDepends
/usr/include/QtWaylandGlobal/QtWaylandGlobalVersion
/usr/include/QtWaylandGlobal/qtwaylandglobal-config.h
/usr/include/QtWaylandGlobal/qtwaylandglobalversion.h
/usr/include/QtWlShellIntegration/6.6.1/QtWlShellIntegration/private/qwayland-wayland.h
/usr/include/QtWlShellIntegration/6.6.1/QtWlShellIntegration/private/qwaylandwlshellintegration_p.h
/usr/include/QtWlShellIntegration/6.6.1/QtWlShellIntegration/private/qwaylandwlshellsurface_p.h
/usr/include/QtWlShellIntegration/6.6.1/QtWlShellIntegration/private/wayland-wayland-client-protocol.h
/usr/include/QtWlShellIntegration/QtWlShellIntegration
/usr/include/QtWlShellIntegration/QtWlShellIntegrationDepends
/usr/include/QtWlShellIntegration/QtWlShellIntegrationVersion
/usr/include/QtWlShellIntegration/qtwlshellintegrationversion.h
/usr/lib64/cmake/Qt6/FindWaylandkms.cmake
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtWaylandTestsConfig.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandEglPlatformIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandEglPlatformIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandEglPlatformIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandEglPlatformIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandEglPlatformIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandEglPlatformIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Gui/Qt6QWaylandIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6DrmEglServerBufferPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6DrmEglServerBufferPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6DrmEglServerBufferPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6DrmEglServerBufferPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6DrmEglServerBufferPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6DrmEglServerBufferPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandBradientDecorationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandBradientDecorationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandBradientDecorationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandBradientDecorationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandBradientDecorationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandBradientDecorationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandEglClientBufferPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandEglClientBufferPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandEglClientBufferPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandEglClientBufferPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandEglClientBufferPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandEglClientBufferPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandFullScreenShellV1IntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandFullScreenShellV1IntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandFullScreenShellV1IntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandFullScreenShellV1IntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandFullScreenShellV1IntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandFullScreenShellV1IntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandIviShellIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandIviShellIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandIviShellIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandIviShellIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandIviShellIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandIviShellIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandQtShellIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandQtShellIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandQtShellIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandQtShellIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandQtShellIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandQtShellIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandWlShellIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandWlShellIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandWlShellIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandWlShellIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandWlShellIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandWlShellIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandXdgShellIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandXdgShellIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandXdgShellIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandXdgShellIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandXdgShellIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6QWaylandXdgShellIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6ShmServerBufferPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6ShmServerBufferPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6ShmServerBufferPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6ShmServerBufferPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6ShmServerBufferPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6ShmServerBufferPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6VulkanServerBufferPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6VulkanServerBufferPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6VulkanServerBufferPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6VulkanServerBufferPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6VulkanServerBufferPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6VulkanServerBufferPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientConfig.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientDependencies.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientMacros.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientPlugins.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientTargets.cmake
/usr/lib64/cmake/Qt6WaylandClient/Qt6WaylandClientVersionlessTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6DrmEglServerBufferIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6DrmEglServerBufferIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6DrmEglServerBufferIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6DrmEglServerBufferIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6DrmEglServerBufferIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6DrmEglServerBufferIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglClientBufferIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglClientBufferIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglClientBufferIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglClientBufferIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglClientBufferIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglClientBufferIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglStreamClientBufferIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglStreamClientBufferIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglStreamClientBufferIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglStreamClientBufferIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglStreamClientBufferIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6QWaylandEglStreamClientBufferIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6ShmServerBufferIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6ShmServerBufferIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6ShmServerBufferIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6ShmServerBufferIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6ShmServerBufferIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6ShmServerBufferIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6VulkanServerBufferIntegrationPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6VulkanServerBufferIntegrationPluginConfig.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6VulkanServerBufferIntegrationPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6VulkanServerBufferIntegrationPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6VulkanServerBufferIntegrationPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6VulkanServerBufferIntegrationPluginTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorConfig.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorDependencies.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorMacros.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorPlugins.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorTargets.cmake
/usr/lib64/cmake/Qt6WaylandCompositor/Qt6WaylandCompositorVersionlessTargets.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateConfig.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateDependencies.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateTargets.cmake
/usr/lib64/cmake/Qt6WaylandEglClientHwIntegrationPrivate/Qt6WaylandEglClientHwIntegrationPrivateVersionlessTargets.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateConfig.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateDependencies.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateTargets.cmake
/usr/lib64/cmake/Qt6WaylandEglCompositorHwIntegrationPrivate/Qt6WaylandEglCompositorHwIntegrationPrivateVersionlessTargets.cmake
/usr/lib64/cmake/Qt6WaylandGlobalPrivate/Qt6WaylandGlobalPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandGlobalPrivate/Qt6WaylandGlobalPrivateConfig.cmake
/usr/lib64/cmake/Qt6WaylandGlobalPrivate/Qt6WaylandGlobalPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandGlobalPrivate/Qt6WaylandGlobalPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandGlobalPrivate/Qt6WaylandGlobalPrivateTargets.cmake
/usr/lib64/cmake/Qt6WaylandGlobalPrivate/Qt6WaylandGlobalPrivateVersionlessTargets.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsConfig.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsConfigVersion.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsDependencies.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsTargets.cmake
/usr/lib64/cmake/Qt6WaylandScannerTools/Qt6WaylandScannerToolsVersionlessTargets.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateConfig.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateDependencies.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateTargets.cmake
/usr/lib64/cmake/Qt6WlShellIntegrationPrivate/Qt6WlShellIntegrationPrivateVersionlessTargets.cmake
/usr/lib64/libQt6WaylandClient.prl
/usr/lib64/libQt6WaylandClient.so
/usr/lib64/libQt6WaylandCompositor.prl
/usr/lib64/libQt6WaylandCompositor.so
/usr/lib64/libQt6WaylandEglClientHwIntegration.prl
/usr/lib64/libQt6WaylandEglClientHwIntegration.so
/usr/lib64/libQt6WaylandEglCompositorHwIntegration.prl
/usr/lib64/libQt6WaylandEglCompositorHwIntegration.so
/usr/lib64/libQt6WlShellIntegration.prl
/usr/lib64/libQt6WlShellIntegration.so
/usr/lib64/pkgconfig/Qt6WaylandClient.pc
/usr/lib64/pkgconfig/Qt6WaylandCompositor.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt6WaylandClient.so.6
/usr/lib64/libQt6WaylandClient.so.6.6.1
/usr/lib64/libQt6WaylandCompositor.so.6
/usr/lib64/libQt6WaylandCompositor.so.6.6.1
/usr/lib64/libQt6WaylandEglClientHwIntegration.so.6
/usr/lib64/libQt6WaylandEglClientHwIntegration.so.6.6.1
/usr/lib64/libQt6WaylandEglCompositorHwIntegration.so.6
/usr/lib64/libQt6WaylandEglCompositorHwIntegration.so.6.6.1
/usr/lib64/libQt6WlShellIntegration.so.6
/usr/lib64/libQt6WlShellIntegration.so.6.6.1
/usr/lib64/qt6/plugins/platforms/libqwayland-egl.so
/usr/lib64/qt6/plugins/platforms/libqwayland-generic.so
/usr/lib64/qt6/plugins/wayland-decoration-client/libbradient.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-client/libdrm-egl-server.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-client/libshm-emulation-server.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-client/libvulkan-server.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-server/libqt-wayland-compositor-drm-egl-server-buffer.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-server/libqt-wayland-compositor-shm-emulation-server.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-server/libqt-wayland-compositor-vulkan-server.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-server/libqt-wayland-compositor-wayland-egl.so
/usr/lib64/qt6/plugins/wayland-graphics-integration-server/libqt-wayland-compositor-wayland-eglstream-controller.so
/usr/lib64/qt6/plugins/wayland-shell-integration/libfullscreen-shell-v1.so
/usr/lib64/qt6/plugins/wayland-shell-integration/libivi-shell.so
/usr/lib64/qt6/plugins/wayland-shell-integration/libqt-shell.so
/usr/lib64/qt6/plugins/wayland-shell-integration/libwl-shell-plugin.so
/usr/lib64/qt6/plugins/wayland-shell-integration/libxdg-shell.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/qtwaylandscanner

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6wayland/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qt6wayland/715f995f11805ee85601834220c43b082f457ea3
/usr/share/package-licenses/qt6wayland/78fef8f56be8b440aa35115b77ac7f968f3974b7
/usr/share/package-licenses/qt6wayland/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qt6wayland/b073f11f0c81a95ab5e32aa6b5d23a5955a95274
/usr/share/package-licenses/qt6wayland/c26ed387addfc80ff83f3bd34f777d1f764c0a63
/usr/share/package-licenses/qt6wayland/f45ee1c765646813b442ca58de72e20a64a7ddba
